apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUREekNDQWZlZ0F3SUJBZ0lVTGJRekFoc1o5dWZjanE5VlhvbDE3aTk1cHhVd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0Z6RVZNQk1HQTFVRUF3d01NVEF1TVRVeUxqRTRNeTR4TUI0WERUSXlNVEV5T1RBek1UWTFOMW9YRFRNeQpNVEV5TmpBek1UWTFOMW93RnpFVk1CTUdBMVVFQXd3TU1UQXVNVFV5TGpFNE15NHhNSUlCSWpBTkJna3Foa2lHCjl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFxbjBKUURJNkdrakJTUXQydFg4akZlUkNjRDFSQ3RtNHNQcUwKUlNVNER0bHNTN0x3bStianZ4Z3ZaOU5QUkxzMnFNaWlNYmdtbGg2bWNOK0VuRVpGUFhoREVJU0dYNmFRbzV2ZQpVczdBZExuLzVtSC9xVVQ3MzFoVzZkcHovdFpSODBhZjFXd3M4RUh5MDJOQ1BxeEtrQTY5d0dQZi9EaGJaNVFKCml1NFZoMWRLWWNpb1J3Zm5BL0V4SGEwTVM4QWIvZTR6L1NMUnBsWTllOTcxQ0s4MWlETGp1MU1NLzNDMGJiRmcKSkdvRjZXdnBKamFaY1I5UnhPVUdTYWJQTGFiSzdjcnloOXhma3A4cEl5QzJGVlhGLzVyZGozeFdHbDMwYUlQSQp5UFhLQngzaEhqblBYM3MrYmtzK0NNOFRZbnhlVWRkcHRrT0ZyR3RKWVhMZ2V4WHV0UUlEQVFBQm8xTXdVVEFkCkJnTlZIUTRFRmdRVTlkSVJ1WjRIT1ZrSmNYZVBxU0QyOWRSMEZJY3dId1lEVlIwakJCZ3dGb0FVOWRJUnVaNEgKT1ZrSmNYZVBxU0QyOWRSMEZJY3dEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQwpBUUVBZE1SRUo4Qk93OFpNSGQrMmQvNUYxWi94b3BIaUM4a08rVGpPU3lEaG9vODRtZ0ZjZjFqeEJ1aGkrbEFXCnNabjZLWEJIYWF1dFFlVHBOZVFJNW5MYXI0TCtzdEpNZW1vWkZnN2pzSDNLV1dyd3g5L1RqVTg2MkIvS2xNZ0EKRDdrK2tOS0FpR0FhZWpSRUdoYS82L0M5dmE1UnYydTIxVnl6MXA1N3NMM1ZaWEs2dkNkU2I0VjRWTllrRjQrUwpmQkdrMER2bHd3R3JUbWVPZ1FJTkxjMmlXNG5oYjVFUWxKNS9QYXNHRGpvSnFzWWhhR0hsbmhKdTBDYVFwandsClY0S052VHlpQjh4b2lDbm9yV0FxRkhMcXJzSTFhcTR1RkgwbnhDeGFDMHpjNDZVbllpSDFXeFBTMU5VUHAvU3cKL1ROU2NjbkZvNGEzZFhZQitibzB0aXE1ZVE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://192.168.1.10:16443
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: cWpEczVkYndYMGQ1RDRjU3Y1alkrckJOV3RVZ1B2bHovVElGMEpmckh6dz0K
